### ISSUE TITLE
cannot use payload

### ISSUE THREAD

**Issue by Casanova402** [allfro/pymetasploit#14]
`from metasploit.msfrpc import MsfRpcClient

client = MsfRpcClient('1234', ssl=False)
payload = client.modules.use('payload', 'windows/meterpreter_reverse_tcp')
`
This is what I did, and it shows:
`Traceback (most recent call last):
  File "/Users/billwu/PycharmProjects/Test/test.py", line 5, in <module>
    payload = client.modules.use('payload', 'windows/meterpreter_reverse_tcp')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/metasploit/msfrpc.py", line 1670, in use
    return PayloadModule(self.rpc, mname)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/metasploit/msfrpc.py", line 1572, in __init__
    super(PayloadModule, self).__init__(rpc, 'payload', payload)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/metasploit/msfrpc.py", line 1326, in __init__
    setattr(self, k, self._info.get(k))
AttributeError: can't set attribute
`

**Comment by 0xPawn** [comment]
Change it to:
windows/meterpreter/reverse_tcp instead of windows/meterpreter_reverse_tcp
