### ISSUE TITLE
can't get db.hosts response content.

### ISSUE THREAD

**Issue by smarttang** [allfro/pymetasploit#30]
`
#coding:utf-8
from metasploit.msfrpc import MsfRpcClient
import ssl
from pprint import pprint

ssl._create_default_https_context = ssl._create_unverified_context

def msf():
    # try:
    client = MsfRpcClient(server="172.17.0.2", password="fuckyou",port=65433, ssl=True)

    print client.call('db.hosts',{})

`

run results:
`
[root@96ae07bd6a32 /]# python func/test.py 
Traceback (most recent call last):
  File "func/test.py", line 87, in <module>
    msf()
  File "func/test.py", line 12, in msf
    print client.call('db.hosts',{})
  File "/usr/lib/python2.7/site-packages/metasploit/msfrpc.py", line 236, in call
    raise MsfRpcError(result['error_message'])
metasploit.msfrpc.MsfRpcError: ActiveRecord::ConnectionNotEstablished
`

how to get db.hosts???

**Comment by DanMcInerney** [comment]
It doesn't look like you're connected to a database? When you boot into msfconsole do you see an error saying could not connect to DB?
